### ISSUE TITLE
Capacity overflow when decoding CBOR payloads 

### ISSUE THREAD

**Issue by kevin-valerio** [yatima-inc/sp-ipld#14]
When decoding certain CBOR-encoded payloads using this function, the application may panic with a "capacity overflow" error message indicating an incorrect calculated length.

For example, when decoding the following payload using `decode()`:

```
DagCborCodec
.decode(ByteCursor::new(vec![123, 154, 58, 116, 110, 36, 0, 0, 0]))
.unwrap_or(Ipld::Bool(false))
```

While debugging, it has been figured out that the calculated length is `11113323046889324544`, which leads to an over-sized vector allocation in the memory.

This issue could potentially cause a denial-of-service or other memory-related problems when processing malformed CBOR payloads.

**Comment by samuelburnham** [comment]
This repo is no longer maintained, you can use https://github.com/ipld/libipld instead
